# Generated by Django 4.2.7 on 2023-11-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=1000, verbose_name='title picture link')),
                ('ranking', models.CharField(max_length=200)),
            ],
        ),
    ]
