# Generated by Django 4.2.7 on 2023-11-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_game_ranks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.CharField(max_length=1000, verbose_name='picture link'),
        ),
    ]
